version: "3.9"
services:
  realsense_ros2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      #target: librealsense
    tty: true
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: bash -c "source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 launch realsense2_camera rs_launch.py align_depth.enable:=true enable_color:=true"
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'  